// Generated by Skyramp v1.3.35 on 2026-07-22 21:19:02.746784913 +0000 UTC m=+951.119359051
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language javascript \
// 		--output dashboard_panel_absolute_range_validation.spec.js \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests/Dashboards \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/dashboard_panel_absolute_range_validation_trace.zip

const { test, expect, navigateToBase } = require("../utils/enhanced-baseFixtures.js");
import { ingestion } from "./utils/dashIngestion.js";
import PageManager from "../../pages/page-manager.js";
import {
  createDashboardWithPanelTime,
  cleanupDashboard,
} from "./utils/panelTimeSetup.js";

test.describe.configure({ mode: "parallel" });

test.describe("Dashboard Panel Time - Absolute Range Validation", () => {
  test.beforeEach(async ({ page }) => {
    await navigateToBase(page);
    await ingestion(page);
  });

  test("should reject a backwards absolute time range on the panel time picker and accept a corrected valid range", async ({ page }) => {
    test.setTimeout(618000);

    const pm = new PageManager(page);
    const timestamp = Date.now();
    const dashboardName = `Dashboard_AbsoluteRangeValidation_${timestamp}`;
    const panelName = `Panel_AbsoluteRangeValidation_${timestamp}`;

    /*----- Setup: create dashboard with a panel-specific time range enabled -----*/
    const { panelId } = await createDashboardWithPanelTime(page, pm, {
      dashboardName,
      panelName,
      panelTimeEnabled: true,
      panelTimeRange: "15-m",
    });

    /*----- Open the panel-level time picker and switch to the Absolute tab -----*/
    await pm.dashboardPanelTime.clickPanelTimePicker(panelId);
    await pm.dashboardPanelTime.dateTimeMenu.waitFor({ state: "visible", timeout: 5000 });
    await pm.dashboardPanelTime.dateTimeMenu.locator('[data-test="date-time-absolute-tab"]').click();

    const startTimeInput = pm.dashboardPanelTime.dateTimeMenu
      .locator('[data-test="datetime-start-time"]')
      .getByRole("textbox");
    const endTimeInput = pm.dashboardPanelTime.dateTimeMenu
      .locator('[data-test="datetime-end-time"]')
      .getByRole("textbox");
    const rangeErrorLocator = pm.dashboardPanelTime.dateTimeMenu.locator('[data-test="date-time-range-error"]');

    /*----- Reject path: end time before start time on the same day -----*/
    await startTimeInput.fill("12:00:00");
    await endTimeInput.fill("10:00:00");
    await pm.dashboardPanelTime.dateTimeMenu.locator('[data-test="date-time-apply-btn"]').click();

    await expect(rangeErrorLocator).toHaveText("End time must be after start time");
    await expect(pm.dashboardPanelTime.dateTimeMenu).toBeVisible();

    /*----- Accept path: fix the range (start < end) and re-apply -----*/
    await startTimeInput.fill("08:00:00");
    await endTimeInput.fill("10:00:00");
    await pm.dashboardPanelTime.dateTimeMenu.locator('[data-test="date-time-apply-btn"]').click();

    await pm.dashboardPanelTime.dateTimeMenu.waitFor({ state: "hidden", timeout: 5000 });
    await expect(pm.dashboardPanelTime.panelTimePickerBtn(panelId)).toContainText("08:00:00");
    await expect(pm.dashboardPanelTime.panelTimePickerBtn(panelId)).toContainText("10:00:00");

    /*----- Cleanup -----*/
    await cleanupDashboard(page, pm, dashboardName);
  });
});
