// Generated by Skyramp v1.3.34 on 2026-07-14 22:59:29.882076084 +0000 UTC m=+440.911190933
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output about_copy_version_info.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/about_copy_version_info_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
    permissions: ['clipboard-read', 'clipboard-write'],
});

test('should copy full build diagnostics to clipboard and show confirmation toast when Copy version info is clicked', async ({ page }) => {
    test.setTimeout(505000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5080");
    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();
    await page.goto("http://localhost:5080/web/about?org_identifier=default");
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await expect(page.locator("[data-test=\"about-copy-version-info-btn\"]")).toHaveText("Copy version info");

    await page.locator("[data-test=\"about-copy-version-info-btn\"]").click();

    await expect(page.getByText("Copied to clipboard").first()).toBeVisible();
});
