// Generated by Skyramp v1.3.34 on 2026-07-14 23:34:54.905565615 +0000 UTC m=+377.460749280
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language javascript \
// 		--output dashboard-datetime-trigger-stale-apply.spec.js \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/dashboard_datetime_trigger_stale_apply_trace.zip

// Import of required libraries
const { test, getValue, newSkyrampPlaywrightPage, expect } = require('@skyramp/skyramp');
const assert = require('assert');

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(372000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    await page.goto("http://localhost:5080/web/login");

    const playwrightRequest0 = {
        "owner": "root@example.com",
        "title": "testbot-datetime-trigger-check"
    };

    await page.locator("[data-test=\"login-user-id-field\"]").fill(getValue(playwrightRequest0, "owner"));
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();
    await page.goto("http://localhost:5080/web/dashboards?org_identifier=default");

    const existingDashboardRow = page.getByRole("cell", { name: getValue(playwrightRequest0, "title"), exact: true });
    if (await existingDashboardRow.isVisible().catch(() => false)) {
      await existingDashboardRow.click();
    } else {
      await page.getByRole("button", { name: "New dashboard", exact: true }).click();
      await page.locator("[data-test=\"add-dashboard-name-field\"]").fill(getValue(playwrightRequest0, "title"));
      // Wait to finish any potential hydration
      await page.waitForTimeout(1500);
      const responsePromise0 = page.waitForResponse("**/api/**/dashboards**");
      await page.locator("[data-test=\"o-dialog-primary-btn\"]").click();
      const response0 = await responsePromise0;
      expect(response0.status()).toBe(200);
    }

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    // Before state: the dashboard's global date-time trigger shows the applied default range.
    const dateTimeTrigger = page.locator("[data-test=\"dashboard-global-date-time-picker\"]");
    await expect(dateTimeTrigger).toHaveText("Past 15 Minutes");

    await page.getByText("Past 15 Minutes").click();
    await page.locator("[data-test=\"date-time-relative-6-h-btn\"]").click();
    await page.keyboard.press("Escape");

    // After state: without pressing Apply, the trigger must still show the last APPLIED
    // range ("Past 15 Minutes"), not the pending "Past 6 Hours" selection. This documents
    // the regression from removing appliedDisplayValue/markApplied/triggerLabel in DateTime.vue
    // -- the trigger now advertises a range no query has actually run against.
    await expect(dateTimeTrigger).toHaveText("Past 15 Minutes");

    assert.strictEqual(pageErrors.length, 0, `Unexpected page errors: ${pageErrors.map((e) => e.message).join(', ')}`);
});
