// Generated by Skyramp v1.3.35 on 2026-07-23 17:12:08.544684718 +0000 UTC m=+744.809857762
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language javascript \
// 		--output date_time_trigger_shows_unapplied_range.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/date-time-trigger-shows-unapplied-range_trace.zip

// Import of required libraries
const { test, expect, getValue, newSkyrampPlaywrightPage } = require('@skyramp/skyramp');
const assert = require('assert');

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1145000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);

    const pageErrors = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5080/login");
    await page.goto("http://localhost:5080/");

    const playwrightRequest0 = {
        "owner": "root@example.com",
        "title": "testbot-dt-regression"
    };

    await page.locator("[data-test=\"login-user-id-field\"]").fill(getValue(playwrightRequest0, "owner"));
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();
    await page.goto("http://localhost:5080/web/logs?org_identifier=default");
    await page.locator("[data-test=\"date-time-btn\"]").getByText("Past 15 Minutes").click();
    await page.locator("[data-test=\"date-time-absolute-tab\"]").click();
    await page.evaluate(() => Array.from(document.querySelectorAll('input[data-test*="time"]')).map(el => ({dataTest: el.getAttribute('data-test'), value: el.value, type: el.type})));
    await page.locator("button").nth(50).locator("path").click();
    await page.keyboard.press("Escape");
    await page.keyboard.press("Escape");
    await page.goto("http://localhost:5080/web/dashboards?org_identifier=default");
    await page.locator("[data-test=\"dashboard-new\"]").click();
    await page.locator("[data-test=\"add-dashboard-name-field\"]").fill(getValue(playwrightRequest0, "title"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/**/dashboards**");
    await page.locator("[data-test=\"o-dialog-primary-btn\"]").click();
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    // Before state: the dashboard's date-time trigger (autoApply=false) shows the
    // currently-applied range.
    await expect(page.locator("[data-test=\"date-time-btn\"]")).toHaveText("Past 15 Minutes");
    await page.getByText("Past 15 Minutes").click();
    await page.locator("[data-test=\"date-time-relative-6-h-btn\"]").click();
    await page.keyboard.press("Escape");

    // Bug documentation: closing the dropdown WITHOUT clicking Apply must leave the
    // previously-applied range in place. The trigger currently updates live to the
    // pending selection instead, so this assertion is expected to FAIL until the
    // applied-vs-pending distinction (removed markApplied/appliedDisplayValue) is restored.
    await expect(page.locator("[data-test=\"date-time-btn\"]")).toHaveText("Past 15 Minutes");

    expect(pageErrors).toHaveLength(0);
});
