// Generated by Skyramp v1.3.35 on 2026-07-23 17:15:07.737543692 +0000 UTC m=+924.002716747
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language javascript \
// 		--output date_time_editable_range_input_apply.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/date-time-editable-range-input-apply_trace.zip

// Import of required libraries
const { test, expect, newSkyrampPlaywrightPage } = require('@skyramp/skyramp');
const assert = require('assert');

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(71000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);

    const pageErrors = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5080/web/logs?org_identifier=default");
    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();
    await page.locator("[data-test=\"date-time-btn\"]").getByText("Past 15 Minutes").click();
    await page.locator("[data-test=\"date-time-absolute-tab\"]").click();
    await page.locator("[data-test=\"date-time-btn-range-input\"]").fill("2026/07/20 09:00:00 - 2026/07/20 10:30:00");
    await page.locator("[data-test=\"date-time-btn-range-input\"]").press("Enter");
    await expect(page.getByRole("textbox", { name: ":00:00" }).first()).toHaveValue("09:00:00");
    await expect(page.getByRole("textbox", { name: ":00:00" }).last()).toHaveValue("10:30:00");
    await expect(page.getByRole("heading", { name: "Event Date, July 2026" })).toBeVisible();
    await expect(page.getByRole("button", { name: "Monday, July 20, 2026" })).toHaveAttribute("aria-pressed", "true");

    expect(pageErrors).toHaveLength(0);
});
