// Generated by Skyramp v1.3.34 on 2026-07-14 23:38:59.734125294 +0000 UTC m=+622.289308969
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language javascript \
// 		--output datetime-range-input-edit-commit-cancel.spec.js \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/datetime_range_input_edit_trace.zip

// Import of required libraries
const { test, newSkyrampPlaywrightPage, expect } = require('@skyramp/skyramp');
const assert = require('assert');

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(260000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    await page.goto("http://localhost:5080/web/dashboards?org_identifier=default");
    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();
    await page.waitForLoadState('networkidle');
    await page.goto("http://localhost:5080/web/logs?org_identifier=default");
    await page.locator("[data-test=\"date-time-btn\"]").getByText("Past 15 Minutes").waitFor({ state: 'visible', timeout: 10000 });
    await page.locator("[data-test=\"date-time-btn\"]").getByText("Past 15 Minutes").click();
    await page.locator("[data-test=\"date-time-absolute-tab\"]").click();
    await page.keyboard.press("Escape");

    const rangeInput = page.locator("[data-test=\"date-time-btn-range-input\"]");
    await rangeInput.fill("2026/07/10 09:00:00 - 2026/07/10 10:00:00");
    await page.keyboard.press("Enter");
    // Commit on Enter: the toolbar trigger input reflects the exact range that was typed.
    await expect(rangeInput).toHaveValue("2026/07/10 09:00:00 - 2026/07/10 10:00:00");

    await rangeInput.fill("not-a-valid-range");
    await page.keyboard.press("Escape");
    // Escape cancels the in-progress edit: the input reverts to the last committed range,
    // not the invalid text that was typed.
    await expect(rangeInput).toHaveValue("2026/07/10 09:00:00 - 2026/07/10 10:00:00");

    assert.strictEqual(pageErrors.length, 0, `Unexpected page errors: ${pageErrors.map((e) => e.message).join(', ')}`);
});
