// Generated by Skyramp v1.3.35 on 2026-07-22 18:24:11.938562762 +0000 UTC m=+757.429834136
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output datetime_trigger_stale_without_apply.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/datetime_trigger_stale_without_apply_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(440000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    await page.goto("http://localhost:5080/");
    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();
    await page.goto("http://localhost:5080/web/metrics?org_identifier=default");
    await page.getByText("Past 15 Minutes").click();
    await expect(page.locator('[data-test="date-time-btn"]')).toContainText("Past 15 Minutes");
    await page.locator("[data-test=\"date-time-relative-6-h-btn\"]").click();
    // The Metrics Explorer's date-time picker has auto-apply disabled (auto-apply-dashboard
    // defaults to false on DateTimePickerDashboard — see web/src/plugins/metrics/Index.vue),
    // so selecting "6" Hours here does NOT press Apply. The trigger button should therefore
    // keep showing the previously-applied range ("Past 15 Minutes") until Apply is clicked.
    // This assertion documents a regression: DateTime.vue's trigger now renders the pending
    // selection (getDisplayValue) directly instead of the last-applied value, so it already
    // shows "Past 6 Hours" here even though no query has actually been re-run yet.
    await expect(page.locator('[data-test="date-time-btn"]')).toContainText("Past 15 Minutes");
    await page.keyboard.press("Escape");

    expect(pageErrors).toHaveLength(0);
});
