// Generated by Skyramp v1.3.35 on 2026-07-22 18:28:40.884577503 +0000 UTC m=+1026.375848877
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output datetime_range_editable_input_commit.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/datetime_range_editable_input_commit_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(138000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    await page.goto("http://localhost:5080/web/logs?org_identifier=default");
    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();
    await page.locator("[data-test=\"date-time-btn\"]").getByText("Past 15 Minutes").click();
    await page.locator("[data-test=\"date-time-absolute-tab\"]").click();
    await page.locator("[data-test=\"date-time-btn-range-input\"]").fill("2026/01/01 01:01:01 - 2026/01/02 02:02:02");
    await page.locator("[data-test=\"date-time-btn-range-input\"]").press("Enter");
    await expect(page.locator('[data-test="datetime-start-time"] input[type="text"]')).toHaveValue("01:01:01");
    await expect(page.locator('[data-test="datetime-end-time"] input[type="text"]')).toHaveValue("02:02:02");
    await page.keyboard.press("Escape");

    expect(pageErrors).toHaveLength(0);
});
