// Generated by Skyramp v1.3.37 on 2026-08-07 22:57:19.860444216 +0000 UTC m=+712.744211374
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output duplicate_function_copy_suffix_collision.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/duplicate_copy_suffix_collision_trace.zip

// Import of required libraries
import { test, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

// Page Object imports
const { LoginPage } = require('../pages/generalPages/loginPage.js');
const FunctionsPage = require('../pages/functionsPages/functionsPage.js');

// Test data
const testEmail = "root@example.com";
const testPassword = "Complexpass#123";
const orgIdentifier = "default";

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }, testInfo) => {
    test.setTimeout(60000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    const skyrampPage = newSkyrampPlaywrightPage(page, testInfo);

    // Module instantiation
    const loginPage = new LoginPage(skyrampPage);
    const functionsPage = new FunctionsPage(skyrampPage);

    /*----- Login -----*/
    await skyrampPage.goto("http://localhost:5080/web/pipeline/functions?org_identifier=default");
    // HIGH: using LoginPage POM properties for login form
    await loginPage.userIdInput.fill(testEmail);
    await loginPage.passwordInput.fill(testPassword);
    await loginPage.loginButton.click();

    /*----- Navigate to Functions (relative URL preserves cookie domain) -----*/
    await skyrampPage.waitForLoadState('networkidle');
    await skyrampPage.evaluate(() => { window.location.href = '/web/pipeline/functions?org_identifier=default'; });
    await skyrampPage.waitForLoadState('networkidle');
    await skyrampPage.waitForTimeout(2000);

    /*----- Duplicate test_fn when test_fn_copy already exists (collision scenario) -----*/
    // UNMAPPED: row-scoped duplicate button not in POM
    await skyrampPage.locator('[data-test="o2-table-row-0"] [data-test="function-list-duplicate-function-btn"]').click();

    /*----- Assert form shows test_fn_copy even when name already exists -----*/
    await expect(skyrampPage).toHaveURL(/action=duplicate/);
    await expect(skyrampPage.locator('[data-test="add-function-name-input-trigger"]')).toContainText('test_fn_copy');
    await expect(skyrampPage.getByText('Add Function')).toBeVisible();

    expect(pageErrors).toHaveLength(0);
});
