// Generated by Skyramp v1.3.37 on 2026-08-07 22:57:23.858801895 +0000 UTC m=+716.742569063
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output duplicate_function_saves_new_not_overwrite.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/duplicate_saves_new_trace.zip

// Import of required libraries
import { test, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

// Page Object imports
const { LoginPage } = require('../pages/generalPages/loginPage.js');
const FunctionsPage = require('../pages/functionsPages/functionsPage.js');

// Test data
const testEmail = "root@example.com";
const testPassword = "Complexpass#123";
const orgIdentifier = "default";

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }, testInfo) => {
    test.setTimeout(68000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    const skyrampPage = newSkyrampPlaywrightPage(page, testInfo);

    // Module instantiation
    const loginPage = new LoginPage(skyrampPage);
    const functionsPage = new FunctionsPage(skyrampPage);

    /*----- Login -----*/
    await skyrampPage.goto("http://localhost:5080/web/pipeline/functions?org_identifier=default");
    // HIGH: using LoginPage POM properties for login form
    await loginPage.userIdInput.fill(testEmail);
    await loginPage.passwordInput.fill(testPassword);
    await loginPage.loginButton.click();

    /*----- Navigate to Functions -----*/
    await skyrampPage.waitForLoadState('networkidle');
    await Promise.all([
        skyrampPage.waitForURL('**/pipeline/functions**', { timeout: 15000 }),
        skyrampPage.evaluate(() => { window.location.href = '/web/pipeline/functions?org_identifier=default'; }).catch(() => {})
    ]);
    await skyrampPage.waitForTimeout(2000);

    /*----- Duplicate test_fn and save -----*/
    // UNMAPPED: function-list-duplicate-function-btn not in POM (added by this PR)
    await skyrampPage.locator('[data-test="o2-table-row-0"] [data-test="function-list-duplicate-function-btn"]').click();
    await skyrampPage.waitForTimeout(1500);
    // PREFERRED: clickSaveButton is timing-aware (waitForTimeout 2000)
    const responsePromise0 = skyrampPage.waitForResponse("**/api/**/functions**");
    await functionsPage.clickSaveButton();
    const response0 = await responsePromise0;

    /*----- Assert both functions exist — source not overwritten -----*/
    await expect(skyrampPage.locator('[data-test="function-list-name-cell-test_fn"]')).toBeVisible();
    await expect(skyrampPage.locator('[data-test="function-list-name-cell-test_fn_copy"]')).toBeVisible();
    expect(response0.status()).toBe(200);
    await expect(skyrampPage.getByText('2 Functions')).toBeVisible();

    expect(pageErrors).toHaveLength(0);
});
