// Generated by Skyramp v1.3.37 on 2026-08-07 22:51:42.174235791 +0000 UTC m=+375.058002970
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output duplicate_function_copy_name_prefill.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/duplicate_function_trace.zip

// Import of required libraries
import { test, getValue, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

// Page Object imports
const { LoginPage } = require('../pages/generalPages/loginPage.js');
const FunctionsPage = require('../pages/functionsPages/functionsPage.js');

// Test data
const testEmail = "root@example.com";
const testPassword = "Complexpass#123";
const testFunctionName = "test_fn";
const testFunctionBody = ".";
const orgIdentifier = "default";

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page, context }, testInfo) => {
    test.setTimeout(274000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    const skyrampPage = newSkyrampPlaywrightPage(page, testInfo);

    // Module instantiation
    const loginPage = new LoginPage(skyrampPage);
    const functionsPage = new FunctionsPage(skyrampPage);

    /*----- Login -----*/
    await skyrampPage.goto("http://localhost:5080");
    // HIGH: using LoginPage POM properties for login form
    await loginPage.userIdInput.fill(testEmail);
    await loginPage.passwordInput.fill(testPassword);
    await loginPage.loginButton.click();

    /*----- Navigate to Functions -----*/
    await skyrampPage.goto("http://localhost:5080/web/pipeline/functions?org_identifier=default");
    await skyrampPage.waitForTimeout(2000);

    /*----- Create test function -----*/
    // PREFERRED: clickAddFunctionButton is timing-aware
    await functionsPage.clickAddFunctionButton(orgIdentifier);
    // HIGH: fillFunctionName covers trigger click + input fill
    await functionsPage.fillFunctionName(testFunctionName);
    await skyrampPage.waitForTimeout(1500);
    await skyrampPage.keyboard.press("Enter");
    await skyrampPage.waitForTimeout(3000);

    // HIGH: enterFunctionCode uses Monaco API (timing-aware with waitForTimeout(1000))
    await functionsPage.enterFunctionCode(testFunctionBody);
    await skyrampPage.waitForTimeout(1500);
    // PREFERRED: clickSaveButton is timing-aware
    await functionsPage.clickSaveButton();
    await skyrampPage.waitForTimeout(3000);

    /*----- Assert function saved in list -----*/
    await expect(skyrampPage.locator(`[data-test="function-list-name-cell-${testFunctionName}"]`)).toBeVisible();

    /*----- Click Duplicate -----*/
    // UNMAPPED: function-list-duplicate-function-btn is not in the POM (added by this PR)
    await skyrampPage.locator("[data-test=\"function-list-duplicate-function-btn\"]").click();

    /*----- Assert duplicate form pre-fill -----*/
    await expect(skyrampPage).toHaveURL(/action=duplicate/);
    await expect(skyrampPage.locator('[data-test="add-function-name-input-trigger"]')).toContainText('test_fn_copy');
    await expect(skyrampPage.getByText('Add Function')).toHaveText('Add Function');

    expect(pageErrors).toHaveLength(0);
});
