// Generated by Skyramp v1.3.37 on 2026-08-07 20:34:15.812566042 +0000 UTC m=+2922.173892234
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output function_duplicate.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/function_duplicate_trace.zip

// Import of required libraries
import { test, getValue, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

// POM imports
const FunctionsPage = require('../pages/functionsPages/functionsPage.js');
const { LoginPage } = require('../pages/generalPages/loginPage.js');

// Test data
const TEST_EMAIL = "root@example.com";
const TEST_PASSWORD = "Complexpass#123";
const TEST_ORG = "default";
const FUNC1_NAME = "testfunc1";
const FUNC1_CODE = '.foo = "bar"';
const FUNC2_NAME = "testfunc2";
const FUNC2_CODE = '.bar = "baz"';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(5343000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    // Page error handler — assert no uncaught JS errors at the end
    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    // Module instantiation
    const loginPage = new LoginPage(page);
    const functionsPage = new FunctionsPage(page);

    /*----- Login -----*/
    await page.goto("http://localhost:5080");
    await loginPage.userIdInput.fill(TEST_EMAIL);
    await loginPage.passwordInput.fill(TEST_PASSWORD);
    await loginPage.loginButton.click();
    // Assert redirect to authenticated app after login
    await expect(page).toHaveURL(/\/web\//);

    /*----- Navigate to Functions -----*/
    await page.goto(`http://localhost:5080/web/pipeline/functions?org_identifier=${TEST_ORG}`);
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    /*----- Create testfunc1 -----*/
    await functionsPage.addFunctionButton.click();
    // Fill function name (trigger click + field fill)
    await functionsPage.fillFunctionName(FUNC1_NAME);
    // Press Enter to confirm name — triggers intermediate API call (may return error for empty body)
    const responsePromise0 = page.waitForResponse("**/api/**/functions**");
    await functionsPage.functionNameInputField.press("Enter");
    const response0 = await responsePromise0;
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    // Set VRL code via Monaco API (raw evaluate — ensures Vue v-model debounce syncs via setValue)
    await page.evaluate((code) => {
      const editors = window.monaco?.editor?.getEditors?.() || [];
      for (const ed of editors) {
        const model = ed.getModel();
        if (model) { model.setValue(code); return code; }
      }
    }, FUNC1_CODE);
    // Wait to finish any potential hydration and Monaco v-model debounce (500ms)
    await page.waitForTimeout(1500);
    const responsePromise3 = page.waitForResponse("**/api/**/functions**");
    await functionsPage.clickSaveButton();
    const response3 = await responsePromise3;
    // Assert testfunc1 was saved successfully
    expect(response3.status()).toBe(200);
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    /*----- Duplicate testfunc1 (scenario 1: isUpdated=false, creates new function) -----*/
    await page.locator("[data-test=\"function-list-duplicate-function-btn\"]").click();
    // PR behavior: assert form opens in Add mode (isUpdated=false) with _copy suffix
    await expect(page.getByText('Add Function')).toBeVisible();
    await expect(page.getByText(`${FUNC1_NAME}_copy`)).toBeVisible();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise4 = page.waitForResponse("**/api/**/functions**");
    await functionsPage.clickSaveButton();
    const response4 = await responsePromise4;
    // Assert duplicate saved as new function (not overwrite)
    expect(response4.status()).toBe(200);
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    /*----- Create testfunc2 (for multiple-duplicates scenario) -----*/
    await functionsPage.addFunctionButton.click();
    await functionsPage.fillFunctionName(FUNC2_NAME);
    const responsePromise5 = page.waitForResponse("**/api/**/functions**");
    await functionsPage.functionNameInputField.press("Enter");
    const response5 = await responsePromise5;
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    // Set VRL code for testfunc2 via raw evaluate
    await page.evaluate((code) => {
      const editors = window.monaco?.editor?.getEditors?.() || [];
      for (const ed of editors) {
        const model = ed.getModel();
        if (model) { model.setValue(code); return code; }
      }
    }, FUNC2_CODE);
    // Wait to finish any potential hydration and Monaco v-model debounce (500ms)
    await page.waitForTimeout(1500);
    const responsePromise6 = page.waitForResponse("**/api/**/functions**");
    await functionsPage.clickSaveButton();
    const response6 = await responsePromise6;
    // Assert testfunc2 was saved successfully
    expect(response6.status()).toBe(200);
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    /*----- Duplicate testfunc2 (scenario 2: multiple duplicates → 4 functions total) -----*/
    const responsePromise7 = page.waitForResponse("**/api/**/functions**");
    await page.locator("[data-test=\"o2-table-row-1\"] [data-test=\"function-list-duplicate-function-btn\"]").click();
    const response7 = await responsePromise7;
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await functionsPage.clickSaveButton();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);

    /*----- Duplicate testfunc1 again (scenario 3: no-collide — testfunc1_copy already exists) -----*/
    const responsePromise8 = page.waitForResponse("**/api/**/functions**");
    await page.locator("[data-test=\"o2-table-row-3\"] [data-test=\"function-list-duplicate-function-btn\"]").click();
    const response8 = await responsePromise8;
    // PR behavior: duplicate button still opens form in Add mode even for collision scenario
    await expect(page.getByText('Add Function')).toBeVisible();

    // Assert no uncaught JS errors during the test
    expect(pageErrors).toHaveLength(0);
});
