// Generated by Skyramp v1.3.34 on 2026-07-14 23:41:17.474358698 +0000 UTC m=+760.029542373
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language javascript \
// 		--output otime-24hour-input-validation.spec.js \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/otime_24hour_input_validation_trace.zip

// Import of required libraries
const { test, expect, newSkyrampPlaywrightPage } = require('@skyramp/skyramp');
const assert = require('assert');

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(117000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    await page.goto("http://localhost:5080/web/logs?org_identifier=default");
    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();
    await page.locator("[data-test=\"date-time-btn\"]").getByText("Past 15 Minutes").click();
    await page.locator("[data-test=\"date-time-absolute-tab\"]").click();

    const startTimeInput = page.getByRole("textbox", { name: ":00:00" }).nth(0);
    const endTimeInput = page.getByRole("textbox", { name: ":00:00" }).nth(1);

    await startTimeInput.fill("14:30:45");
    await page.keyboard.press("Tab");
    // Valid 24-hour input commits on blur.
    await expect(startTimeInput).toHaveValue("14:30:45");

    const endTimeBefore = await endTimeInput.inputValue();
    await endTimeInput.fill("99:99:99");
    await page.keyboard.press("Tab");
    // Invalid input (out-of-range hour/minute/second) is rejected: the field reverts
    // to its last valid value instead of accepting the malformed text.
    await expect(endTimeInput).toHaveValue(endTimeBefore);

    assert.strictEqual(pageErrors.length, 0, `Unexpected page errors: ${pageErrors.map((e) => e.message).join(', ')}`);
});
