// Generated by Skyramp v1.3.35 on 2026-07-23 17:16:35.562140259 +0000 UTC m=+1011.827313294
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language javascript \
// 		--output otime_24hr_invalid_input_reverts.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/otime-24hr-invalid-input-reverts_trace.zip

// Import of required libraries
const { test, expect, newSkyrampPlaywrightPage } = require('@skyramp/skyramp');
const assert = require('assert');

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(63000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);

    const pageErrors = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5080/web/logs?org_identifier=default");
    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();
    await page.locator("[data-test=\"date-time-btn\"]").getByText("Past 15 Minutes").click();
    await page.locator("[data-test=\"date-time-absolute-tab\"]").click();
    // Before state: the Start time field holds a valid 24-hour value (derived from
    // "now" at recording/replay time, so read it rather than hardcoding a clock value).
    const startTimeInput = page.getByRole("textbox", { name: ":00:00" }).nth(0);
    const validStartTime = await startTimeInput.inputValue();
    await startTimeInput.fill("99:99:99");
    await startTimeInput.press("Enter");
    // After state: the malformed "99:99:99" is rejected and the field reverts to
    // its prior valid value rather than accepting the out-of-range input.
    await expect(startTimeInput).toHaveValue(validStartTime);

    expect(pageErrors).toHaveLength(0);
});
