// Generated by Skyramp v1.3.35 on 2026-07-22 18:30:14.714210352 +0000 UTC m=+1120.205481736
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output otime_24_hour_text_input_validation.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/otime_24_hour_text_input_validation_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(83000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    await page.goto("http://localhost:5080/web/logs?org_identifier=default");
    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();
    await page.locator("[data-test=\"date-time-btn\"]").getByText("Past 15 Minutes").click();
    await page.locator("[data-test=\"date-time-absolute-tab\"]").click();
    const startTimeInput = page.locator('[data-test="datetime-start-time"] input[type="text"]');
    const validStartTime = await startTimeInput.inputValue();
    await startTimeInput.fill("25:99:99");
    await page.keyboard.press("Tab");
    await expect(startTimeInput).toHaveValue(validStartTime);
    await page.keyboard.press("Escape");

    expect(pageErrors).toHaveLength(0);
});
