// Generated by Skyramp v1.3.37 on 2026-08-10 16:43:51.87646751 +0000 UTC m=+680.772612551
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output toggle_group_reorder_via_drag.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/toggle_group_reorder_via_drag_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { LoginPage } from '../pages/generalPages/loginPage.js';

// Test data
const userEmail = process.env["ZO_ROOT_USER_EMAIL"] || "root@example.com";
const userPassword = process.env["ZO_ROOT_USER_PASSWORD"] || "Complexpass#123";

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(74000);

    const errors: Error[] = [];
    page.on('pageerror', (e) => errors.push(e));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    const skyrampPage = newSkyrampPlaywrightPage(page);

    /*----- Module instantiation -----*/
    const loginPage = new LoginPage(skyrampPage);

    /*----- Login -----*/
    await skyrampPage.goto("http://localhost:5080/web/traces?org_identifier=default");
    await loginPage.fillLoginForm(userEmail, userPassword);
    await loginPage.submitLoginForm();

    /*----- Switch to Traces mode, then back to Spans (round-trip) -----*/
    await skyrampPage.locator('[data-test="traces-search-mode-traces-btn"]').click();
    await expect(skyrampPage.locator('[data-test="traces-search-mode-traces-btn"]')).toHaveAttribute('aria-pressed', 'true');

    await skyrampPage.locator('[data-test="traces-search-mode-spans-btn"]').click();
    await expect(skyrampPage.locator('[data-test="traces-search-mode-spans-btn"]')).toHaveAttribute('aria-pressed', 'true');

    expect(errors).toHaveLength(0);
});
