// Generated by Skyramp v1.3.37 on 2026-08-10 18:22:01.015542589 +0000 UTC m=+500.508428383
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output toggle_group_alert_type_filter.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/toggle_group_alert_type_filter_trace.zip

// Import of required libraries
import { test, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(735000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5080");
    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();
    // Wait for network activities to finish
    await page.waitForTimeout(55291);

    await page.goto("http://localhost:5080/web/alerts?org_identifier=default");
    await page.locator("[data-test=\"tab-scheduled\"]").click();
    await expect(page).toHaveURL(/tab=scheduled/);
    await expect(page.locator("[data-test=\"tab-scheduled\"]")).toHaveAttribute('aria-pressed', 'true');
});
