// Generated by Skyramp v1.3.37 on 2026-08-10 16:43:53.250813966 +0000 UTC m=+682.146959017
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output toggle_group_traces_tab_bar_reorder.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/toggle_group_traces_tab_bar_reorder_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { LoginPage } from '../pages/generalPages/loginPage.js';

// Test data
const userEmail = process.env["ZO_ROOT_USER_EMAIL"] || "root@example.com";
const userPassword = process.env["ZO_ROOT_USER_PASSWORD"] || "Complexpass#123";

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    const errors: Error[] = [];
    page.on('pageerror', (e) => errors.push(e));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    const skyrampPage = newSkyrampPlaywrightPage(page);

    /*----- Module instantiation -----*/
    const loginPage = new LoginPage(skyrampPage);

    /*----- Login -----*/
    await skyrampPage.goto("http://localhost:5080/web/traces?org_identifier=default");
    await loginPage.fillLoginForm(userEmail, userPassword);
    await loginPage.submitLoginForm();

    /*----- Assert initial toggle group render state -----*/
    await expect(skyrampPage.getByRole("heading", { name: "Start sending traces to" })).toHaveText("Start sending traces to OpenObserve");
    await expect(skyrampPage.locator('[data-test="traces-search-mode-spans-btn"]')).toHaveAttribute('aria-pressed', 'true');

    expect(errors).toHaveLength(0);
});
