// Generated by Skyramp v1.3.37 on 2026-08-10 18:26:42.319848 +0000 UTC m=+781.812733804
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output toggle_group_folder_scope_switch.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/toggle_group_folder_scope_switch_trace.zip

// Import of required libraries
import { test, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(61000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5080/web/alerts?org_identifier=default");
    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();
    await page.locator("[data-test=\"alert-list-search-across-folders-toggle\"]").click();
    await expect(page.locator("[data-test=\"alert-list-search-across-folders-toggle\"]")).toHaveAttribute('aria-pressed', 'true');
});
