// Generated by Skyramp v1.3.38 on 2026-08-13 01:33:35.439191175 +0000 UTC m=+1034.081475425
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output function_list_duplicate_saves_as_new_function.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/function_list_duplicate_saves_as_new_function_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5080");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(128000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    // Credential(s) read from the environment — never recorded into this file. Set these before running.
    if (process.env.SKYRAMP_UI_PASSWORD === undefined) {
        throw new Error("SKYRAMP_UI_PASSWORD is not set: this test replays a login and needs that credential in the environment");
    }
    const loginPassword = process.env.SKYRAMP_UI_PASSWORD ?? "";

    const errors: Error[] = [];
    page.on('pageerror', err => errors.push(err));

    await page.goto(`${baseUrl}/web/login`);
    await page.waitForLoadState('networkidle');
    // kept inline: loginPage.js — login() uses ZO_ROOT_USER_EMAIL/ZO_ROOT_USER_PASSWORD env vars; this test uses SKYRAMP_UI_PASSWORD; credentials cannot be safely bridged
    // kept inline: dashLogin.js — same as loginPage.js; credential env-var mismatch
    await page.locator('[data-testid="login-user-id-field"]').waitFor({ state: 'visible', timeout: 10000 });
    await page.getByTestId("login-user-id-field").fill("root@example.com");
    await page.getByTestId("login-password-field").fill(loginPassword);
    await page.getByTestId("login-sign-in").click();
    await page.goto(`${baseUrl}/web/pipeline/functions?org_identifier=default`);
    await page.waitForLoadState('networkidle');
    // kept inline: sanityPage.js — CommonJS module.exports; TypeScript ESM import not configured; o2-table-row-0 matches are incidental
    // kept inline: commonActions.js — CommonJS module.exports; no selectors in this test's flow matched by shared actions
    // kept inline: functionsFormValidationPage.js — CommonJS module.exports; Tier-2 file; no duplicate-button POM coverage
    // kept inline: functionsPage.js — CommonJS module.exports; Tier-2 file; no duplicate-button POM coverage
    // kept inline: pipelinesEP.js — CommonJS module.exports; pipelines POM, not functions-specific
    // kept inline: pipelinesPage.js — CommonJS module.exports; pipelines POM, not functions-specific
    // kept inline: workflowsPage.js — CommonJS module.exports; workflows POM, not functions-specific
    await expect(page.getByTestId("o2-table-pagination-actions")).toContainText("1 Functions");
    // kept inline: function-list-duplicate-function-btn — no POM coverage (new PR button)
    await page.getByTestId("function-list-duplicate-function-btn").click();
    await expect(page).toHaveURL(/action=duplicate/);
    await expect(page.getByTestId("add-function-name-input-trigger")).toContainText("test_fn_for_duplicate_copy");
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/**/functions**");
    await page.getByTestId("add-function-save-btn").click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByTestId("o2-table-pagination-actions")).toContainText("2 Functions");
    await expect(page.getByTestId("o2-table-row-0")).toContainText("test_fn_for_duplicate_copy");
    expect(errors).toHaveLength(0);
});
