// Generated by Skyramp v1.3.38 on 2026-08-13 01:25:47.750783612 +0000 UTC m=+566.393067862
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output function_list_duplicate_opens_prefilled_form.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/function_list_duplicate_opens_prefilled_form_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5080");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(852000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    // Credential(s) read from the environment — never recorded into this file. Set these before running.
    if (process.env.SKYRAMP_UI_PASSWORD === undefined) {
        throw new Error("SKYRAMP_UI_PASSWORD is not set: this test replays a login and needs that credential in the environment");
    }
    const loginPassword = process.env.SKYRAMP_UI_PASSWORD ?? "";

    const errors: Error[] = [];
    page.on('pageerror', err => errors.push(err));

    await page.goto(baseUrl);
    await page.waitForLoadState('networkidle');
    // kept inline: loginPage.js — login() uses ZO_ROOT_USER_EMAIL/ZO_ROOT_USER_PASSWORD env vars; this test uses SKYRAMP_UI_PASSWORD; credentials cannot be safely bridged
    // kept inline: dashLogin.js — same as loginPage.js; credential env-var mismatch
    await page.locator('[data-testid="login-user-id-field"]').waitFor({ state: 'visible', timeout: 10000 });
    await page.getByTestId("login-user-id-field").fill("root@example.com");
    await page.getByTestId("login-password-field").fill(loginPassword);
    await page.getByTestId("login-sign-in").click();
    await page.goto(`${baseUrl}/web/functions?org_identifier=default`);
    await page.waitForLoadState('networkidle');
    // Wait for network activities to finish
    await page.waitForTimeout(10748);

    await page.goto(`${baseUrl}/web/pipeline/functions?org_identifier=default`);
    await page.waitForLoadState('networkidle');
    // kept inline: functionsFormValidationPage.js — CommonJS module.exports; TypeScript ESM import not configured for this Playwright runner; no duplicate-button coverage
    // kept inline: sanityPage.js — CommonJS module.exports; general sanity page POM, not specific to duplicate flow
    // kept inline: pipelinesEP.js — CommonJS module.exports; pipelines POM, not functions-specific
    // kept inline: pipelinesPage.js — CommonJS module.exports; pipelines POM, not functions-specific
    // kept inline: workflowsPage.js — CommonJS module.exports; workflows POM, not functions-specific
    // kept inline: logsPage.js — logs-vrl-function-editor is incidental (reused component); this test exercises functions page, not logs page
    // kept inline: logsQueryPage.js — imported dependency of logsPage.js; no selector match in this test context
    // kept inline: ingestionPage.js — imported dependency of matched POM; no selector match for functions-page actions
    // kept inline: managementPage.js — imported dependency of matched POM; no selector match for functions-page actions
    // kept inline: commonActions.js — imported dependency of matched POM; no selector match for functions-page actions
    // kept inline: oselectHelpers.js — imported dependency of matched POM; no selector match for functions-page actions
    // kept inline: alertsPage.js — matched only on generic Editor content; alerts POM not applicable to functions
    // kept inline: alertCreationWizard.js — imported dependency of alertsPage.js; not applicable
    // kept inline: alertManagement.js — imported dependency of alertsPage.js; not applicable
    // kept inline: alertBulkOperations.js — imported dependency of alertsPage.js; not applicable
    await page.getByTestId("function-list-add-function-btn").click();
    await page.getByTestId("add-function-name-input-trigger").click();

    const playwrightRequest0: Record<string, any> = {"name": "test_fn_for_duplicate"};

    await page.getByTestId("add-function-name-input-input").fill(getValue(playwrightRequest0, "name"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/**/functions**");
    await page.getByTestId("add-function-name-input-input").press("Enter");
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest1: Record<string, any> = {"function": ".level = downcase!(.level)"};

    await page.getByTestId("logs-vrl-function-editor").getByRole("textbox", { name: "Editor content" }).fill(getValue(playwrightRequest1, "function"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/**/functions**");
    await page.getByTestId("add-function-save-btn").click();
    const response1 = await responsePromise1;
    expect(response1.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto(`${baseUrl}/web/login`);
    await page.waitForLoadState('networkidle');
    await page.locator('[data-testid="login-user-id-field"]').waitFor({ state: 'visible', timeout: 10000 });
    await page.getByTestId("login-user-id-field").fill("root@example.com");
    await page.getByTestId("login-password-field").fill(loginPassword);
    await page.getByTestId("login-sign-in").click();
    await page.goto(`${baseUrl}/web/pipeline/functions?org_identifier=default`);
    // kept inline: functionsPage.js — function-list-duplicate-function-btn has no POM coverage (button added by this PR, not yet in any POM)
    await page.getByTestId("function-list-duplicate-function-btn").click();
    await expect(page).toHaveURL(/action=duplicate/);
    await expect(page.getByTestId("add-function-name-input-trigger")).toContainText("test_fn_for_duplicate_copy");
    await expect(page.getByTestId("add-function-save-btn")).toBeVisible();
    expect(errors).toHaveLength(0);
});
