// Generated by Skyramp v1.3.38 on 2026-08-13 01:36:00.889162579 +0000 UTC m=+625.463029061
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output functions_toolbar_toggle_active_state.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/functions_toolbar_toggle_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5080");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1039000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    // Credential(s) read from the environment — never recorded into this file. Set these before running.
    if (process.env.SKYRAMP_UI_PASSWORD === undefined) {
        throw new Error("SKYRAMP_UI_PASSWORD is not set: this test replays a login and needs that credential in the environment");
    }
    const loginPassword = process.env.SKYRAMP_UI_PASSWORD ?? "";

    // kept inline: dashLogin.js — CommonJS module; no tsconfig for TypeScript/CJS interop in Skyramp runner; methods depend on process.env.ZO_BASE_URL not set in Skyramp executor
    // kept inline: loginPage.js — CommonJS module; no tsconfig for TypeScript/CJS interop in Skyramp runner; login() depends on process.env.ZO_BASE_URL not set in Skyramp executor
    // kept inline: functionsFormValidationPage.js — CommonJS module; no tsconfig for TypeScript/CJS interop; POM navigate methods depend on process.env.ZO_BASE_URL/ORGID
    // kept inline: functionsPage.js — CommonJS module; no tsconfig for TypeScript/CJS interop; navigate()/clickAddFunctionButton() depend on process.env.ZO_BASE_URL/ORGID

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    /*----- Login -----*/
    await page.goto(`${baseUrl}/web/login`);
    await page.waitForLoadState('networkidle');
    await page.locator('[data-testid="login-user-id-field"]').waitFor({ state: 'visible', timeout: 10000 });
    await page.getByTestId("login-user-id-field").fill("root@example.com");
    await page.getByTestId("login-password-field").fill(loginPassword);
    await page.getByTestId("login-sign-in").click();
    await expect(page).toHaveURL(/web\/pipeline\/functions|web\/$/);

    /*----- Navigate to Add Function -----*/
    await page.goto(`${baseUrl}/web/pipeline/functions?org_identifier=default`);
    await page.waitForLoadState('networkidle');
    await page.locator('[data-testid="function-list-add-function-btn"]').waitFor({ state: 'visible', timeout: 10000 });
    await page.getByTestId("function-list-add-function-btn").click();
    await expect(page).toHaveURL(/action=add/);
    await expect(page.getByRole("heading", { name: "Enter Function Name" })).toBeVisible();

    /*----- Assert VRL toggle option is active (data-state=on) -----*/
    await expect(page.getByTestId("function-transform-type-vrl-option")).toContainText("VRL");
    await expect(page.getByTestId("function-transform-type-vrl-option")).toHaveAttribute("data-state", "on");

    expect(pageErrors).toHaveLength(0);
});
