// Generated by Skyramp v1.3.38 on 2026-08-13 03:14:27.053158003 +0000 UTC m=+586.221272735
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language javascript \
// 		--output functions_toolbar_vrl_active_state.spec.js \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/functions_toolbar_vrl_active_state_trace.zip

// Import of required libraries
const { test, expect, getBaseUrl, newSkyrampPlaywrightPage } = require('@skyramp/skyramp');
const FunctionsPage = require('../../pages/functionsPages/functionsPage.js');

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5080");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }, testInfo) => {
    test.setTimeout(952000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);

    // Page error capture (Rule 3 — assert no JS exceptions)
    const pageErrors = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    // Wrap playwright page with Skyramp page
    const skyrampPage = newSkyrampPlaywrightPage(page, testInfo);

    // Credential(s) read from the environment — never recorded into this file. Set these before running.
    if (process.env.SKYRAMP_UI_PASSWORD === undefined) {
        throw new Error("SKYRAMP_UI_PASSWORD is not set: this test replays a login and needs that credential in the environment");
    }
    const loginPassword = process.env.SKYRAMP_UI_PASSWORD ?? "";

    // Module instantiation
    const functionsPage = new FunctionsPage(skyrampPage);

    /*----- Login -----*/
    await skyrampPage.goto(baseUrl);
    await skyrampPage.waitForLoadState('networkidle');
    await skyrampPage.locator('[data-test="login-user-id-field"]').waitFor({ state: 'visible', timeout: 10000 });
    await skyrampPage.getByTestId("login-user-id-field").fill("root@example.com");
    await skyrampPage.getByTestId("login-password-field").fill(loginPassword);
    await skyrampPage.getByTestId("login-sign-in").click();

    /*----- Navigate to Functions and open Add Function form -----*/
    await functionsPage.navigate('default');
    await functionsPage.clickAddFunctionButton();
    // Post-action: form is open when the name trigger is visible
    await expect(functionsPage.functionNameTrigger).toBeVisible();

    /*----- Assert VRL toggle option is active (data-state="on") -----*/
    // The VRL option is the default active language; the new OFormToggleGroup
    // exposes the selected state via data-state="on" on the OToggleGroupItem.
    await expect(functionsPage.vrlRadio).toContainText("VRL");
    await expect(functionsPage.vrlRadio).toHaveAttribute('data-state', 'on');

    // No page-level JS errors
    expect(pageErrors).toHaveLength(0);
});
