// Generated by Skyramp v1.3.38 on 2026-08-13 03:31:22.497477201 +0000 UTC m=+831.701484447
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output function_list_duplicate_saves_as_new.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/function_list_duplicate_saves_as_new_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
// POM imports
import { LoginPage } from '../../pages/generalPages/loginPage';
const FunctionsPage = require('../../pages/functionsPages/functionsPage');

const pageTimeout = 15000;

// Test data
const functionName = "test_source_fn";
const functionCode = '.status = "processed"';

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5080");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1143000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    // Credential(s) read from the environment — never recorded into this file. Set these before running.
    if (process.env.SKYRAMP_UI_PASSWORD === undefined) {
        throw new Error("SKYRAMP_UI_PASSWORD is not set: this test replays a login and needs that credential in the environment");
    }
    const loginPassword = process.env.SKYRAMP_UI_PASSWORD ?? "";

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // Module instantiation
    const loginPage = new LoginPage(page);
    const functionsPage = new FunctionsPage(page);

    /*----- Login -----*/
    await page.goto(baseUrl);
    await loginPage.fillLoginForm("root@example.com", loginPassword);
    await loginPage.submitLoginForm();
    await page.waitForURL(/\/web\//, { timeout: 30000 });

    await page.goto(`${baseUrl}/web/pipeline/functions?org_identifier=default`);
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    /*----- Create source function -----*/
    // raw waitForResponse blocks dropped — createVRLFunction wrapping method used instead
    if (!await page.getByText(functionName, { exact: true }).isVisible().catch(() => false)) {
        await functionsPage.createVRLFunction(functionName, functionCode);
    }

    /*----- Verify source function in list -----*/
    await expect(page.getByTestId("o2-table-cell-name")).toContainText(functionName);

    /*----- Duplicate the function -----*/
    await page.getByTestId("function-list-duplicate-function-btn").click();
    await expect(functionsPage.functionNameTrigger).toContainText(`${functionName}_copy`);

    /*----- Save the duplicate -----*/
    // raw waitForResponse dropped — clickSaveButton is timing-aware (waitForTimeout 2000ms)
    await page.waitForTimeout(1500);
    await functionsPage.clickSaveButton();

    /*----- Verify both functions exist in the list -----*/
    await expect(page.getByTestId("o2-table-row-0")).toContainText(`${functionName}_copy`);
    await expect(page.getByTestId("o2-table-row-1")).toContainText(functionName);
    await expect(page.getByTestId("o2-table-pagination-actions")).toContainText("2 Functions");

    expect(errors).toHaveLength(0);
});
