// Generated by Skyramp v1.3.38 on 2026-08-13 03:31:33.527736237 +0000 UTC m=+842.731743463
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output function_list_duplicate_btn_visible_per_row.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/function_list_duplicate_btn_visible_per_row_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
// POM imports
import { LoginPage } from '../../pages/generalPages/loginPage';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5080");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(71000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    // Credential(s) read from the environment — never recorded into this file. Set these before running.
    if (process.env.SKYRAMP_UI_PASSWORD === undefined) {
        throw new Error("SKYRAMP_UI_PASSWORD is not set: this test replays a login and needs that credential in the environment");
    }
    const loginPassword = process.env.SKYRAMP_UI_PASSWORD ?? "";

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // Module instantiation
    const loginPage = new LoginPage(page);

    /*----- Login -----*/
    await page.goto(`${baseUrl}/web/pipeline/functions?org_identifier=default`);
    await loginPage.fillLoginForm("root@example.com", loginPassword);
    await loginPage.submitLoginForm();
    await page.waitForURL(/\/web\//, { timeout: 30000 });
    await page.waitForLoadState('networkidle');
    await page.getByTestId("o2-table-row-0").waitFor({ state: 'visible', timeout: 30000 });

    /*----- Assert duplicate button visible on every row -----*/
    await expect(page.getByTestId("o2-table-row-0")).toContainText("Duplicate function");
    await expect(page.getByTestId("o2-table-row-1")).toContainText("Duplicate function");
    await expect(page.getByTestId("o2-table-pagination-actions")).toContainText("2 Functions");

    expect(errors).toHaveLength(0);
});
