// Generated by Skyramp v1.3.38 on 2026-08-13 01:36:18.464865166 +0000 UTC m=+1197.107149416
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output function_list_duplicate_button_renders.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/function_list_duplicate_button_renders_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5080");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(83000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    // Credential(s) read from the environment — never recorded into this file. Set these before running.
    if (process.env.SKYRAMP_UI_PASSWORD === undefined) {
        throw new Error("SKYRAMP_UI_PASSWORD is not set: this test replays a login and needs that credential in the environment");
    }
    const loginPassword = process.env.SKYRAMP_UI_PASSWORD ?? "";

    const errors: Error[] = [];
    page.on('pageerror', err => errors.push(err));

    await page.goto(`${baseUrl}/web/login`);
    await page.waitForLoadState('networkidle');
    // kept inline: loginPage.js — login() uses ZO_ROOT_USER_EMAIL/ZO_ROOT_USER_PASSWORD env vars; this test uses SKYRAMP_UI_PASSWORD
    // kept inline: dashLogin.js — same credential env-var mismatch
    await page.locator('[data-testid="login-user-id-field"]').waitFor({ state: 'visible', timeout: 10000 });
    await page.getByTestId("login-user-id-field").fill("root@example.com");
    await page.getByTestId("login-password-field").fill(loginPassword);
    await page.getByTestId("login-sign-in").click();
    await page.waitForLoadState('networkidle');
    // kept inline: logsPage.js — matched o2-table-row-0/1 selectors are incidental; this test exercises the functions page, not the logs page
    // kept inline: ingestionPage.js — imported dependency of logsPage.js; no direct selector match for functions-page actions
    // kept inline: managementPage.js — imported dependency of logsPage.js; no direct selector match for functions-page actions
    // kept inline: oselectHelpers.js — imported dependency of logsPage.js; no direct selector match for functions-page actions
    // kept inline: functionsPage.js — CommonJS module.exports; no duplicate-button POM coverage (new PR button)
    // kept inline: functionsFormValidationPage.js — CommonJS module.exports; no POM coverage for this flow
    // kept inline: sanityPage.js — CommonJS module.exports; no POM coverage for duplicate button
    // kept inline: commonActions.js — CommonJS module.exports; no direct selector match
    // kept inline: pipelinesEP.js — CommonJS module.exports; pipelines POM not applicable
    // kept inline: pipelinesPage.js — CommonJS module.exports; pipelines POM not applicable
    // kept inline: workflowsPage.js — CommonJS module.exports; workflows POM not applicable
    await page.goto(`${baseUrl}/web/pipeline/functions?org_identifier=default`);
    await expect(page).toHaveURL(/pipeline\/functions/);
    await expect(page.getByTestId("o2-table-pagination-actions")).toContainText("2 Functions");
    await expect(page.getByTestId("function-list-duplicate-function-btn")).toHaveCount(2);
    await expect(page.getByTestId("function-list-duplicate-function-btn").first()).toBeVisible();
    await expect(page.getByTestId("o2-table-row-0")).toContainText("Duplicate function");
    await expect(page.getByTestId("o2-table-row-1")).toContainText("Duplicate function");
    expect(errors).toHaveLength(0);
});
