// Generated by Skyramp v1.3.37 on 2026-08-10 23:07:10.852105565 +0000 UTC m=+559.649876949
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output toggle_group_mutation_observer_item_add.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/toggle_group_mutation_observer_trace.zip

// Import of required libraries
import { test, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

// Test data
const BASE_URL = "http://localhost:5080";
const userEmail = "root@example.com";
const userPassword = "Complexpass#123";

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(890000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);

    const errors: Error[] = [];
    page.on('pageerror', (err: Error) => errors.push(err));

    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(BASE_URL);
    await page.locator('[data-test="login-user-id-field"]').fill(userEmail);
    await page.locator('[data-test="login-password-field"]').fill(userPassword);
    await page.locator('[data-test="login-sign-in"]').click();
    await page.waitForLoadState('networkidle');
    await page.goto(`${BASE_URL}/web/traces?org_identifier=default`);

    await expect(page.locator('[data-test="traces-search-mode-spans-btn"]')).toHaveAttribute('aria-pressed', 'true');
    await page.locator('[data-test="traces-search-mode-traces-btn"]').click();
    await expect(page).toHaveURL(/tab=traces/);
    await expect(page.locator('[data-test="traces-search-mode-traces-btn"]')).toHaveAttribute('aria-pressed', 'true');

    expect(errors).toHaveLength(0);
});
