// Generated by Skyramp v1.3.37 on 2026-08-10 23:12:00.386376599 +0000 UTC m=+849.184147983
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output toggle_group_alert_type_selection.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/toggle_group_alert_type_selection_trace.zip

// Import of required libraries
import { test, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

// Test data
const BASE_URL = "http://localhost:5080";
const userEmail = "root@example.com";
const userPassword = "Complexpass#123";

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);

    const errors: Error[] = [];
    page.on('pageerror', (err: Error) => errors.push(err));

    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${BASE_URL}/web/alerts?org_identifier=default`);
    await page.locator('[data-test="login-user-id-field"]').fill(userEmail);
    await page.locator('[data-test="login-password-field"]').fill(userPassword);
    await page.locator('[data-test="login-sign-in"]').click();

    await expect(page.locator('[data-test="tab-all"]')).toHaveAttribute('aria-pressed', 'true');
    await page.locator('[data-test="tab-scheduled"]').click();
    await expect(page).toHaveURL(/tab=scheduled/);
    await expect(page.locator('[data-test="tab-scheduled"]')).toHaveAttribute('aria-pressed', 'true');
    await expect(page.getByRole('heading', { name: 'Alerts' })).toBeVisible();

    expect(errors).toHaveLength(0);
});
