// Generated by Skyramp v1.3.37 on 2026-08-10 22:42:25.884213893 +0000 UTC m=+656.904470665
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output toggle_group_realtime_filter.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/toggle_group_realtime_filter_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', (err: Error) => errors.push(err));

    await page.goto("http://localhost:5080/web/login");
    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();
    await page.goto("http://localhost:5080/web/alerts?org_identifier=default");
    await expect(page.locator("[data-test=\"tab-realTime\"]")).toHaveAttribute('aria-pressed', 'false');
    await page.locator("[data-test=\"tab-realTime\"]").click();
    await expect(page).toHaveURL(/tab=realTime/);
    await expect(page.locator("[data-test=\"tab-realTime\"]")).toHaveAttribute('aria-pressed', 'true');
    expect(errors).toHaveLength(0);
});
